# Site settings
title: Nano Foundation
email: 	
description: "Nano Foundation founded in 2015, as a computer science and research foundation. We are currently working on a 32-bit operating system, called 'NanOS'."
baseurl: ""
url: "http://nano-foundation.github.io"
twitter_username: 
github_username: nano-foundation

# Build settings
markdown: kramdown
permalink: pretty
